Repository JiPyoTak/plandar-server, pull requests merged in 2023-03, with the labels that each got.

#5 버그 이슈 템플릿 추가
  .github/ISSUME_TEMPLATE/bug_report.md
  .github/ISSUME_TEMPLATE/feature_request.md
  .gitignore
Labels: DOC, CHORE

#7 @Transactional() 및 Repository 에러 해결
  package-lock.json
  package.json
  src/api/plan/plan.module.ts
  src/api/plan/plan.repository.ts
  src/api/user/user.module.ts
  src/api/user/user.repository.ts
  src/api/user/user.service.ts
  src/app.module.ts
  src/common/decorator/transaction.decorator.ts
  src/common/middleware/transaction.middleware.ts
  src/common/root.repository.ts
  src/common/transaction.manager.ts
  src/main.ts
Labels: BUG

#8 Github Issue Template이 오타로 인해 적용 안되던 버그 수정
  .github/ISSUM_TEMPLATE/bug_report.md
  .github/ISSUM_TEMPLATE/feature_request.md
Labels: BUG

#10 swagger 설정 추가 및 간단한 예제 작성
  src/api/user/user.controller.ts
  src/api/user/user.service.ts
  src/dto/user/create-user.dto.ts
  src/entity/default.entity.ts
  src/entity/plan.entity.ts
  src/entity/user.entity.ts
  src/main.ts
Labels: FEATURE

#11 Custom Repository Decorator 추가 및 설정
  src/api/plan/plan.module.ts
  src/api/plan/plan.repository.ts
  src/api/user/user.module.ts
  src/api/user/user.repository.ts
  src/common/customRepository.decorator.ts
  src/common/typeOrmEx.module.ts
  src/utils/constants.ts
Labels: FEATURE

#12 일관된 Test Code 작성을 위해 구조 및 예시 코드 확립
  src/api/plan/plan.controller.ts
  src/api/plan/plan.repository.ts
  src/api/plan/plan.service.ts
  test/api/plan/plan.controller.spec.ts
  test/api/plan/plan.service.spec.ts
  test/api/user/user.controller.spec.ts
  test/api/user/user.service.spec.ts
  test/utils/createTestingModule.ts
Labels: TEST

#14 TypeORM Entity 생성 및 적용
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/entity/category.entity.ts
  src/entity/plan.entity.ts
  src/entity/tag.entity.ts
  src/entity/user.entity.ts
  test/api/plan/mock.ts
  test/api/plan/plan.controller.spec.ts
  test/api/plan/plan.service.spec.ts
Labels: FEATURE

#25 User Contoller 테스트 및 비즈니스 로직 생성
  src/api/user/user.controller.ts
  src/api/user/user.service.ts
  src/decorators/user.decorator.ts
  src/guard/jwt-auth.guard.ts
  test/api/user/mock.ts
  test/api/user/user.controller.spec.ts
  test/api/user/user.service.spec.ts
  test/utils/createMockJwtAuthGuard.ts
  test/utils/createTestingModule.ts
Labels: FEATURE, TEST

#30 Tag Api 구현
  src/api/tag/tag.controller.ts
  src/api/tag/tag.module.ts
  src/api/tag/tag.repository.ts
  src/api/tag/tag.service.ts
  src/app.module.ts
  src/dto/tag/args.ts
  src/dto/tag/index.ts
  src/dto/tag/tag-req.dto.ts
  src/dto/tag/tag-res.dto.ts
  test/api/tag/stub.ts
  test/api/tag/tag.controller.spec.ts
  test/api/tag/tag.service.spec.ts
Labels: DOC, FEATURE, TEST

#37 Category Controller 구현
  src/api/category/category.controller.ts
  src/api/category/category.module.ts
  src/api/category/category.repository.ts
  src/api/category/category.service.ts
  src/app.module.ts
  src/dto/category/args.ts
  src/dto/category/category-create-req.dto.ts
  src/dto/category/category-res.dto.ts
  src/dto/category/category-update-req.dto.ts
  src/dto/category/index.ts
  test/api/category/category.controller.spec.ts
  test/api/category/stub.ts
Labels: DOC, FEATURE, TEST

#35 auth service 테스트 및 비즈니스 로직 생성
  package-lock.json
  package.json
  src/api/auth/auth.module.ts
  src/api/auth/auth.service.ts
  src/app.module.ts
  src/decorators/user.decorator.ts
  src/utils/constants.ts
  test/api/auth/auth.service.spec.ts
  test/api/auth/mock.ts
Labels: FEATURE, TEST

#42 oAuth 관련 인증 및 전략 기능 구현
  package-lock.json
  package.json
  src/api/auth/auth.controller.ts
  src/api/auth/auth.module.ts
  src/api/auth/auth.service.ts
  src/api/auth/guards/oauth.guard.ts
  src/api/auth/strategies/oauth.strategy.ts
  src/api/user/user.controller.ts
  src/api/user/user.repository.ts
  src/api/user/user.service.ts
  src/types/index.ts
  src/utils/constants.ts
  test/api/auth/auth.service.spec.ts
Labels: FEATURE

#49 디렉터리 구조 변경 및 함수 인자 변경
  src/api/auth/auth.controller.ts
  src/api/auth/auth.module.ts
  src/api/auth/auth.service.ts
  src/api/auth/strategies/oauth.strategy.ts
  src/api/category/category.module.ts
  src/api/category/category.repository.ts
  src/api/category/category.service.ts
  src/api/plan/plan.module.ts
  src/api/plan/plan.repository.ts
  src/api/tag/tag.module.ts
  src/api/tag/tag.repository.ts
  src/api/tag/tag.service.ts
  src/api/user/user.controller.ts
  src/api/user/user.module.ts
  src/api/user/user.repository.ts
  src/api/user/user.service.ts
  src/common/decorators/custom-repository.decorator.ts
  src/common/decorators/index.ts
  src/common/decorators/skip-auth.decorator.ts
  src/common/decorators/user.decorator.ts
  src/common/filters/http-exception.filter.ts
  src/common/filters/index.ts
  src/common/interceptors/index.ts
  src/common/interceptors/success.interceptor.ts
  src/common/modules/index.ts
  src/common/modules/typeorm-ex.module.ts
  src/dto/category/index.ts
  src/dto/tag/index.ts
  src/dto/user/create-user.dto.ts
  src/dto/user/index.ts
  src/dto/user/user-create.dto.ts
  src/main.ts
  src/types/args/auth.ts
  src/types/args/category.ts
  src/types/args/index.ts
  src/types/args/tag.ts
  src/types/index.ts
  test/api/auth/auth.controller.spec.ts
  test/api/user/user.controller.spec.ts
Labels: REFACTOR

#50 병합시 변경된 테스트 코드 및 argument 수정
  test/api/auth/auth.service.spec.ts
  test/api/auth/mock.ts
  test/api/user/mock.ts
  test/api/user/user.controller.spec.ts
  test/api/user/user.service.spec.ts
Labels: BUG, REFACTOR

#53 이미 존재하는 Tag를 생성하려는 경우 로직 변경
  src/api/tag/tag.service.ts
  test/api/tag/tag.service.spec.ts
Labels: FEATURE

#54 동일한 이름, 색상으로 카테고리 변경시 exception
  src/api/category/category.service.ts
Labels: BUG

#55 전체 파일에 대한 중간 점검 Refactoring
  src/api/auth/auth.controller.ts
  src/api/auth/auth.module.ts
  src/api/auth/auth.service.ts
  src/api/category/category.controller.ts
  src/api/category/category.repository.ts
  src/api/plan/plan.controller.ts
  src/api/plan/plan.repository.ts
  src/api/plan/plan.service.ts
  src/api/tag/tag.controller.ts
  src/api/tag/tag.repository.ts
  src/api/user/user.controller.ts
  src/api/user/user.repository.ts
  src/api/user/user.service.ts
  src/app.module.ts
  src/common/decorators/date-type.decorator.ts
  src/common/decorators/index.ts
  src/common/guards/index.ts
  src/common/guards/jwt-auth.guard.ts
  src/common/guards/oauth.guard.ts
  src/common/pipes/index.ts
  src/common/pipes/parse-date.pipe.ts
  src/common/strategies/index.ts
  src/common/strategies/jwt-auth.strategy.ts
  src/common/strategies/oauth.strategy.ts
  src/dto/category/category-create-req.dto.ts
  src/dto/category/category-res.dto.ts
  src/dto/tag/tag-req.dto.ts
  src/dto/tag/tag-res.dto.ts
  src/dto/user/user-create.dto.ts
  src/entities/category.entity.ts
  src/entities/default.entity.ts
  src/entities/index.ts
  src/entities/plan.entity.ts
  src/entities/tag.entity.ts
  src/entities/user.entity.ts
  src/types/args/auth.ts
  src/types/args/category.ts
  src/types/environment.ts
  src/types/index.ts
  src/types/token.ts
  test/api/auth/auth.controller.spec.ts
  test/api/auth/auth.service.spec.ts
  test/api/auth/stub.ts
  test/api/category/category.controller.spec.ts
  test/api/category/category.service.spec.ts
  test/api/category/stub.ts
  test/api/plan/mock.ts
  test/api/plan/plan.controller.spec.ts
  test/api/plan/plan.service.spec.ts
  test/api/plan/stub.ts
  test/api/tag/stub.ts
  test/api/tag/tag.controller.spec.ts
  test/api/tag/tag.service.spec.ts
  test/api/user/stub.ts
  test/api/user/user.controller.spec.ts
  test/api/user/user.service.spec.ts
  test/utils/create-mock-jwt-auth-guard.ts
  test/utils/create-testing-module.ts
Labels: REFACTOR
